name: Codeception Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:

  ci:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]

    env:
      cache_version: 1 # increment to flush all caches
      PROJECT_ID: weglot-companion
      COMPOSE_INTERACTIVE_NO_CLI: 1
      COMPOSE_FILE: docker-compose.yml:docker-compose.gh.yml

    steps:
      - name: Use docker-compose v2
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: 'v2.4.1'

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Open permissions on output and directories
        run:  chmod 777 dev/tests/tests/_output

      - name: Create composer .env
        run: echo "${{ secrets.COMPOSER_ENV }}" > .env

      - name: Create local config
        run: |
          php -r "file_exists( 'dev/tests/.env' ) || copy( 'dev/tests/.env-dist', 'dev/tests/.env' );"
          printf 'SQ1_UID=%d\nSQ1_GID=%d\n' $(id -u) $(id -g) > dev/docker/.env

      - name: Create composer config files
        run: |
          mkdir -p dev/docker/composer
          printf '{ "config": {}, "repositories": { "packagist": { "type": "composer", "url": "https://packagist.org" } } }' > dev/docker/composer/config.json
          printf '{ "github-oauth": { "github.com": "%s" } }\n' "${{ secrets.GITHUB_TOKEN }}" > dev/docker/composer/auth.json

      - name: Check for Cached Composer Dependencies
        id: cache-composer-dependencies
        uses: actions/cache@v2
        with:
          path: dev/docker/composer/cache
          key: ${{ runner.os }}-${{ env.cache_version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.cache_version }}-composer-

      - name: Create docker network
        run: docker network create --driver=bridge --subnet=172.20.10.0/24 global_proxy
        working-directory: dev/docker

      - name: Start project containers
        run: docker-compose --project-name=${{ env.PROJECT_ID }} up -d --force-recreate
        working-directory: dev/docker

      - name: Install composer dependencies
        run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests composer install --optimize-autoloader -d /application/www
        working-directory: dev/docker

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install --prefer-offline

      - name: Build assets
        run: yarn prod

      - name: Create test databases
        run: |
          mysql -h 127.0.0.1 -uroot -ppassword -e "CREATE DATABASE tribe_weglot_companion_tests;"
          mysql -h 127.0.0.1 -uroot -ppassword -e "CREATE DATABASE tribe_weglot_companion_acceptance;"

      - name: Run unit tests
        run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests php /application/www/vendor/bin/codecept --config "/application/www/dev/tests" run unit
        working-directory: dev/docker

      - name: Run integration tests
        run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests php /application/www/vendor/bin/codecept --config "/application/www/dev/tests" run integration
        working-directory: dev/docker

#      - name: Run functional tests
#        run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests php /application/www/vendor/bin/codecept --config "/application/www/dev/tests" run functional
#        working-directory: dev/docker
#
#       - name: Run acceptance tests
#         run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests php /application/www/vendor/bin/codecept --config "/application/www/dev/tests" run acceptance
#         working-directory: dev/docker
#
#       - name: Run webdriver tests
#         run: docker-compose --project-name=${{ env.PROJECT_ID }} exec -T php-tests php /application/www/vendor/bin/codecept -vvv --config "/application/www/dev/tests" run webdriver
#         working-directory: dev/docker

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-artifacts
          path: dev/tests/tests/_output/
