name: 'ESLint'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install node modules
        run: yarn install --prefer-offline

      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: 'resources/src'
